### ISSUE TITLE
[1.15.2] Does nothing

### ISSUE THREAD

**Issue by NillerMedDild** [CraftTweaker/JEITweaker#1]
It seems like `JEITweaker-1.0.0` is non-functional.

I've tried using it like this:
```java
mods.jei.JEI.hideItem(item);
mods.jei.JEI.addInfo(item, ["This item is disabled.", "If you somehow obtained it, please report it on Enigmatica 5's issue tracker.", "There's a link to it in the Main Menu."]);
```
No errors, but nothing happens. The `item` was of course an actual item.
[logs.zip](https://github.com/CraftTweaker/JEITweaker/files/4497842/logs.zip)

**Comment by jaredlll08** [comment]
You uploaded an empty zip file.
also please don't give me files to download, pastebin the logs

**Comment by NillerMedDild** [comment]
Alright, sorry about that.
crafttweaker.log: https://gist.github.com/NillerMedDild/e5e920917d4910f61fd2a8b7123ca060
latest.log: https://gist.github.com/NillerMedDild/88ba3c9c2f484b00091ad2a6f681d2bf

**Comment by RIKRUS** [comment]
i have same issue, but with error no such member
[logs](https://gist.github.com/RIKRUS/4022834b92b535560815fc2de1ec648f)

**Comment by kindlich** [comment]
@RIKRUS 
Please update to the latest CraftTweaker beta release on CF, that issue should've already been fixed in there.

**Comment by RIKRUS** [comment]
> i have same issue, but with error no such member
> [logs](https://gist.github.com/RIKRUS/4022834b92b535560815fc2de1ec648f)

thanks, it works

**Comment by NillerMedDild** [comment]
Kindlich helped me out, it works fine if I call it normally, outside of loops, so user error - Sorry about that.
