### ISSUE TITLE
Backport to 1.12.2

### ISSUE THREAD

**Issue by TheGoodIdeaFairy** [CraftTweaker/JEITweaker#13]
I don't know enough about the API changes between 1.12 and 1.14 to know if this is reasonable, but if it is feasible a 1.12.2 version would be appreciated.

**Comment by kindlich** [comment]
In 1.12, JEI support was part of CraftTweaker, check this page.
<https://docs.blamejared.com/1.12/en/Mods/JEI/JEI/>
