### ISSUE TITLE
Environmental Recipes missing

### ISSUE THREAD

**Issue by Miaawing** [CraftTweaker/JEITweaker#14]
Found a bad interaction between Environmental Tech/core/energy. recipes are broken in JEI wen JEITweaker is added. have been tested with this modlist. https://i.imgur.com/YwLTFI5.png Recipes in side the machine ''Assembler'' is not showing while playing on a server. have tested this on both the recommened forge version and the latest. 

This is more or less a problem when joining servers. since if you join a SP world beforhand the recipes shows up for that session. but you have to load up SP everytime you join a server that have JEITweaker to see those recipes. :) 

have posted this to Valk's discord aswell :)

client: https://pastebin.com/nzTvn6NF
server :https://pastebin.com/P4THctmw
server debug: https://pastebin.com/2KSaUghD

**Comment by jaredlll08** [comment]
Fixed by Environmental Tech
