### ISSUE TITLE
All JEITweaker Features Only Working On First Load

### ISSUE THREAD

**Issue by Alcates** [CraftTweaker/JEITweaker#16]
I've found that any changes made to JEI by my CT scripts only work directly after the game launch. Using /reload or loading a new world causes the JEI changes to be reverted until the next game restart. This applies to both items and categories.

These are my two .zs files that utilize JEI Tweaker at all:
https://pastebin.com/fbw3azpJ
https://pastebin.com/m0QQVCPS

CT log:
https://pastebin.com/gUNzM1Ds

Game Console Log:
https://pastebin.com/z1th79yF

Game version: 1.16.5
Forge version: forge-36.1.0
CT version: 1.16.5-7.1.0.313
JEIT version: 1.16.5-1.0.1.27

Thanks in advance.

**Comment by jaredlll08** [comment]
In my experience, this is caused by another mod breaking things, your game log is incomplete, can I get your `latest.log` file?

**Comment by Alcates** [comment]
https://gist.github.com/n2galaxy/576c03e4757a91d1ad701d3ad30baac9
Here you go. Sorry about that.

**Comment by jaredlll08** [comment]
So there are a few issues with the log you gave.

https://gist.github.com/n2galaxy/576c03e4757a91d1ad701d3ad30baac9#file-latest-log-L8304-L8311
It seem that `PneumaticCraft` has a broken recipe, this is most likely the main issue, so I would report it to them.

There is also this section, which I'm not sure if it is an actual issue or something you can ignore
https://gist.github.com/n2galaxy/576c03e4757a91d1ad701d3ad30baac9#file-latest-log-L8265-L8294

libvulpes is also doing something weird around here:
https://gist.github.com/n2galaxy/576c03e4757a91d1ad701d3ad30baac9#file-latest-log-L547

Anyway, get the `PneumaticCraft` issue fixed and it will probably resolve this one.

**Comment by Alcates** [comment]
Quick question: Would removing this recipe with a datapack fix the issue or is this something that loads before them?

**Comment by jaredlll08** [comment]
Yep! That should work, even removing the recipe with CraftTweaker should work, all run before JEI

**Comment by Bees-Please** [comment]
Same issue, JEI item purge reverts after a reload. Couldn't find broken recipes in latest.log.

Latest: https://gist.github.com/Bees-Please/1fbbc39b33a4546185b9568685ffb39d
Crafttweaker: https://gist.github.com/Bees-Please/971c305c75eaeedb677fa952f11d6c2c
Script 1: https://gist.github.com/Bees-Please/aed639c2af8323632658d3383fc9afda
Script 2: https://gist.github.com/Bees-Please/dc52c3cfb63c7a78efe92135de4a4c6c

MC: 1.16.5
Forge: 36.1.23
JEI: 7.7.0.106 (Logs generated with 98, updated to 106 and experienced same issue)
CrT: 7.1.0.314
JEIT: 1.0.1.28

**Comment by jaredlll08** [comment]
So your log is riddled with exceptions from loot tables, you really should get those fixed...

Anyway
```
java.lang.IllegalStateException: Failed to find recipe category data for: immersiveengineering:alloy
```
My guess is that you're hiding a category that doesn't exist over here:
https://gist.github.com/Bees-Please/aed639c2af8323632658d3383fc9afda#file-ct-3-1-5_crt-zs-L428

**Comment by Bees-Please** [comment]
Thanks for replying so quick. The loot tables are next on my trello, sadly...

Using the recipeType dump I get the ie:alloy type, I tried removing the line from my script entirely and restarting my client but the issue persisted. Also tried updating supplementaries (Grimmauld's suggestion) to no avail. I can get new logs if needed.

**Comment by jaredlll08** [comment]
New clean logs please

**Comment by Bees-Please** [comment]
Latest: https://gist.github.com/Bees-Please/001af8afc4d585261a7eaf10f99544b9
CrT: https://gist.github.com/Bees-Please/24cc943ed47656334cf08d21dfc372a3

**Comment by jaredlll08** [comment]
```
java.lang.IllegalStateException: Failed to find recipe category data for: immersiveengineering:fertilizer
```
It tells you the error in the log.

Looking at the IE source code, they don't have a category named `fertilizer`

**Comment by Bees-Please** [comment]
So; I commented that line out and reloaded and the issue persisted, but using my last handful of braincells I commented out all of the IE recipetype lines, restarted client, reloaded, and it seems to have fixed it. Attaching logs and script for any other folks experiencing the same issue.

Thank you very much as usual Jared!

Script (updated): https://gist.github.com/Bees-Please/a5b33988b9f8d9eaaf0e14fb7bf8bfc3
Latest: https://gist.github.com/Bees-Please/0f49a98fa3ead93e325403d23d582b01
Crafttweaker: https://gist.github.com/Bees-Please/1477217ee787c91eef2f30908c24803d
