### ISSUE TITLE
JEITweaker doesn't work.

### ISSUE THREAD

**Issue by Dandas52** [CraftTweaker/JEITweaker#19]
JEITweaker doesn't work at all for any of my scripts.

I've ensured that the syntax is correct and that the mod is installed, but in the CraftTweaker logs, any script involving JEItweaker just does not run.

Logs: https://pastebin.com/SgbYny2v

Example script page which uses JEITweaker:  https://pastebin.com/H4JbSyvY

All the other scripts work just fine, but anything involving JEITweaker is completely ignored.

**Comment by jaredlll08** [comment]
I need your latest.log file please

**Comment by Dandas52** [comment]
[latest.log](https://github.com/CraftTweaker/JEITweaker/files/6858580/latest.log)

**Comment by jaredlll08** [comment]
Your JEI state is broken. This has nothing to do with my mod and there is literally nothing I can do about it, you need to go complain to the mods that are breaking it and get them to fix it.

Look in your log for `at mezz.jei`, usually a few lines above it there will be an error message such as:

```
[19:27:26] [Render thread/ERROR]: Found a broken recipe: Thermal Series thermal:devices/plugins/biomesoplenty/tree_extractor_bop_pink_cherry class cofh.thermal.core.util.recipes.device.TreeExtractorMapping
Outputs:
net.minecraftforge.fluids.FluidStack: [[FluidStack{Fluid=Resin, Amount=25}]]
Inputs:
net.minecraft.item.ItemStack: [[1 air minecraft:air], [1 pink_cherry_leaves biomesoplenty:pink_cherry_leaves]]
```
You have like 7 broken recipes.
