### ISSUE TITLE
[Request] Add custom item to JEI

### ISSUE THREAD

**Issue by chimericdream** [CraftTweaker/JEITweaker#2]
On my modded server, we have added crafting recipes for some enchanted books beyond the normal levels. These new books show up when you look at the usage of their ingredients, but I'd like to be able to explicitly add them so they show up in JEI. Is this possible?

**Comment by lublak** [comment]
Yes it would be nice. Also it would be nice if it supports: showWithNBTData.
I don't know if it is possible.

**Comment by jaredlll08** [comment]
Not a clue what `showWithNBTData` is.
