### ISSUE TITLE
Mod wants a newer version of JEI even though the latest one is installed

### ISSUE THREAD

**Issue by vizthex123** [CraftTweaker/JEITweaker#20]
I've got JEI 1.16.5-7.7.1.2 (which is at the top of the list of versions on CurseForge) and JEITweaker 1.16.5-1.0.1.34, but the game says that I need JEI 1.16.5-7.7.1.110.

Could this be fixed? Downgrading JEI fixes it, but I like to have the latest version of all my mods. Log attached.

[latest.log](https://github.com/CraftTweaker/JEITweaker/files/6873212/latest.log)

**Comment by jaredlll08** [comment]
https://github.com/mezz/JustEnoughItems/issues/2427
