### ISSUE TITLE
[Bug] JEI won't show item recipes

### ISSUE THREAD

**Issue by zndrmn** [CraftTweaker/JEITweaker#22]
Versions
Minecraft version 1.16.5
OptiFine version G8
Forge version 36.2.0
JEITweaks version JEITweaker-1.16.5-1.0.1.34
JEI version jei-1.16.5-7.7.1.117

Issue
JEI won't show item recipes once hiding any sort of item from JEI

I can send my scripts, logs etc if needed

**Comment by jaredlll08** [comment]
we need the script and logs.

specifically the latest.log

**Comment by zndrmn** [comment]
Latest.log
https://gist.github.com/zndrmn/57d8aa7a6c90ed6cef78fba33601b249#file-latest-log
Crafttweaker.log
https://gist.github.com/zndrmn/57d8aa7a6c90ed6cef78fba33601b249#file-crafttweaker-log
Scripts
File Tree

Scripts
-------\ JEI > [scripts...](https://gist.github.com/zndrmn/2cab9b8f8b4eb8182de19869a41c2bc1#file-jei)
--------| recipes
----------------\ first aid > [scripts...](https://gist.github.com/zndrmn/3e861368ee268cd5e9ce2de84c82137f#file-first-aid-scripts)
-----------------| minecraft
----------------------------\ button > [scripts...](https://gist.github.com/zndrmn/4744695b0b642ca6d03333e359c163a3#file-button-recipe-scripts)
-----------------------------| pressure plate > [scripts...](https://gist.github.com/zndrmn/bd3671f0b0161cebf5257f1fba1b6b38#file-pp-recipes)
-----------------------------| trapdoor > [scripts...](https://gist.github.com/zndrmn/9c2f28e70b205052a0a9259ce52990e1#file-td-recipes)
-----------------------------[scripts...](https://gist.github.com/zndrmn/3d01a8918df170e5fe1d14b636f04cb9#file-minecraft-script-files)

Hopefully that makes sense
The JEI scripts are what causes the issue

**Comment by jaredlll08** [comment]
```
[14:15:25] [Render thread/ERROR]: Recipe has no output. Antique Atlas antiqueatlas:atlas_clone class hunternif.mc.impl.atlas.item.RecipeAtlasCloning
Outputs:
net.minecraft.item.ItemStack: [[1 air minecraft:air]]
Inputs:
net.minecraft.item.ItemStack: []
[14:15:25] [Render thread/ERROR]: Recipe has no inputs. Antique Atlas antiqueatlas:atlas_combine class hunternif.mc.impl.atlas.item.RecipeAtlasCombining
Outputs:
net.minecraft.item.ItemStack: [[1 antique_atlas antiqueatlas:antique_atlas]]
Inputs:
net.minecraft.item.ItemStack: []
```
Your JEI state is potentially broken.

Try remove Antique Atlas and see if the issue persists?

**Comment by zndrmn** [comment]
New Latest.log
https://gist.github.com/zndrmn/20d89a11f7e9b0bbef678a606d133963#file-latest-log
New crafttweaker.log
https://gist.github.com/zndrmn/0e416a97fdd7e65c0772d62ddd4cfdeb#file-crafttweaker-log

The issue still occurs

**Comment by jaredlll08** [comment]
It is also complaining about:
```
Unknown recipe category: farmersdelight:cooking/farmersdelight:cooking/squid_ink_pasta
```
not sure if that is you trying to use that category, or if it is a mod, either way try remove farmers delight?

No one else has reported this issue, so it is most likely a mod compat issue, try reproduce with just JEITweaker?

**Comment by zndrmn** [comment]
New New Latest.log
https://gist.github.com/zndrmn/41c3709f442344fa6495598c53cf9f8c#file-latest-log
New New crafttweaker.log
https://gist.github.com/zndrmn/82a91abb150a6c2a3654b348e22157df#file-crafttweaker-log

So when pressing R it does nothing and clicking the item it also doesn't show the recipe for it.
It will say 2 recipes (bandage and plaster) are broken because I removed all the mods apart from crafttweaker, JEI, and JEITweaker

**Comment by zndrmn** [comment]
hold up it's working now? lemme start putting mods in and out to see what the problem is

**Comment by jaredlll08** [comment]
The issue stems from:
```zenscript
mods.jei.JEI.hideRegex(".*tin.*");
```
It hides the Crafting Table.

JEI apparently removes recipes made in the Crafting Table when you hide the Crafting Table (I assume if there were alternative crafting tables then it would show them in that table).

You can reproduce this with other blocks as well, such as the furnace:
```zenscript
mods.jei.JEI.hideItem(<item:minecraft:furnace>);
```


There isn't really much I can do about this, it is a JEI "feature", only things I can suggest it to refine the regex or to report to JEI asking for the behaviour to be changed.
