### ISSUE TITLE
version number problem on curse forge 

### ISSUE THREAD

**Issue by AsheX1** [CraftTweaker/JEITweaker#23]
Jul 19, 2021 version : JEITweaker-1.16.5-1.0.1.34.jar

2 days ago : JEITweaker-1.16.5-1.0.1.1.jar

uuu yes how do you go down in version number

thinks its needs to be JEITweaker-1.16.5-1.0.2.1.jar
for it the make sense here but going from versoin 1.0.1.34 to 1.0.1.1 is going backwards....
update curseforge maybe add correct version number

**Comment by jaredlll08** [comment]
Thanks, I've removed the file and made sure it won't happen again.
