### ISSUE TITLE
JEI Tweaker version clash

### ISSUE THREAD

**Issue by RtHiaHB** [CraftTweaker/JEITweaker#26]
I'm getting an error: 

> JEITweaker requires JEI 7.7.1.110 or above.  You are currently running JEI 7.6.1.74.

Here's the problem: I'm running this using Forge for Minecraft 1.16.4.  JEI 7.7.* is for 1.16.5.  I have attached the crash log.  Thanks.

[crash-2021-10-13_10.01.05-fml.txt](https://github.com/CraftTweaker/JEITweaker/files/7338866/crash-2021-10-13_10.01.05-fml.txt)

**Comment by jaredlll08** [comment]
There is literally zero valid reasons to still be using 1.16.4.

1.16.4 mods work on 1.16.5, not the other way around.
