### ISSUE TITLE
Keyword Search

### ISSUE THREAD

**Issue by Xaikii** [CraftTweaker/JEITweaker#27]
I don't know if this is doable in JEI, but how about Keyword searches?
This is something very useful for Vanilla+ or lightweight Packs for a bit more polish.

what I mean:
e.g.
You search for "Redstone" and a Observer is listed.

Something like that could improve how easy the User can find things inside Modpacks.
Optionally also that doing Keyword Searches bypasses Item Hiding, as Keyword searches are 100% manual from the Pack Dev.

**Comment by jaredlll08** [comment]
You can use tags to group items together and then use tag searching to find them, I believe this is what vazkii did in their crucial modpack.

As for a different thing besides tags, go ask JEI, we don't add new JEI features, only expose current features to scripters.
