### ISSUE TITLE
Jei tweaker issue 1.16.5

### ISSUE THREAD

**Issue by fatpally** [CraftTweaker/JEITweaker#29]
### Issue description

gives a error saying to the extent its not loading on start up event (see attached file)
![Jei errror](https://user-images.githubusercontent.com/18649162/147600527-d2d9184c-4015-4cd7-9309-2615628fc851.png)

Currently in a test pack with latest versions of jei and jei tweaker i attempt to load the pack and it gives me that error and i cant go any further

### Steps to reproduce

1. create modpack version with 1.16.5 and latest forge
2. add latest jei
3. add latest jei tweaker
4. attempt to load pack

### Script used

no script used

### The crafttweaker.log file

havent installed crafttweaker

### Minecraft version

1.16

### Forge version

36.2.20

### CraftTweaker version

N/A

### JEITweaker version

1.1.0.48

### JEI version

7.7.1.138

### The latest.log file

https://pastebin.com/mt71H2yr

**Comment by fatpally** [comment]
The log was from my existing modpack and not from my test pack

**Comment by jaredlll08** [comment]
You don't have CraftTweaker installed.

It should tell you that before crashing now
