### ISSUE TITLE
JEI internals been changed

### ISSUE THREAD

**Issue by Shadowdragon019** [CraftTweaker/JEITweaker#30]
### Issue description

Using 1.18.1

From what I know JEI changed their internals and this broke a lot of things

### Script used

https://pastebin.com/rQ8GdHE2

### The crafttweaker.log file

https://pastebin.com/65GvMQry

### Minecraft version

Other

### Forge version

39.1.0

### CraftTweaker version

9.0.81

### JEITweaker version

3.0.0.4

### JEI version

9.4.1.112

### The latest.log file

https://pastebin.com/H5cQ5tRS

**Comment by jaredlll08** [comment]
This was fixed in the 1.18.2 port.
