### ISSUE TITLE
Crash on mod loading

### ISSUE THREAD

**Issue by gabgat** [CraftTweaker/JEITweaker#31]
### Issue description

Minecraft crashes on loading screen saying this: "java.lang.reflect.InvocationTargetException"

### Script used

No script

### The crafttweaker.log file

https://pastebin.com/NkZuqnr0

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.0.32

### CraftTweaker version

9.1.87

### The latest.log file

https://pastebin.com/pWhECHg8

**Comment by jaredlll08** [comment]
Closed by https://github.com/CraftTweaker/JEITweaker/commit/2c2f2051ebed9239dad862bb63466602bc80acae

**Comment by gabgat** [comment]
I don't understand what I need to do, JEITweaker is installed

**Comment by jaredlll08** [comment]
So JEITweaker was installed, but JEI wasn't, so it was crashing, I made it not crash (since it shouldn't).

So you can either install JEI, or update to the new version that should be on curseforge
