### ISSUE TITLE
JEI.hideRecipe() does not hide recipies with nbt data

### ISSUE THREAD

**Issue by Garfield28** [CraftTweaker/JEITweaker#36]
### Issue description

like the title says the function works fine when hiding away normal recipies, but when a mod adds recipies with nbt data it's unable to hide them and they still show up in jei as if nothing happen.

### Steps to reproduce

install computercraft along with crafttweaker, jei and jeitweaker (computercraft is the first example of this that comes to mind)

### Script used

https://pastebin.com/mY3dQwkk

### The crafttweaker.log file

https://pastebin.com/n0hPscKm

### Minecraft version

1.18.2

### Forge version

40.2.0

### CraftTweaker version

9.1.198

### JEITweaker version

3.0.0.9

### JEI version

10.2.1.283

### The latest.log file

https://pastebin.com/7DKpKcPL

**Comment by Garfield28** [comment]
this was opened 5 months ago and no feedback

**Comment by jaredlll08** [comment]
I'm sorry you had to wait so long to get a reply, there seems to have been an issue with notifications.

There is no issue with removing items that use nbt, for example:
```zenscript
import mods.jei.JEI;
var output = <item:minecraft:wooden_sword>.withTag({RepairCost: 0 as int, Enchantments: [{lvl: 1 as short, id: "minecraft:bane_of_arthropods" as string}], display: {Name: "{\"text\":\"custom sword\"}" as string}});
craftingTable.addShapeless("recipe_with_nbt", output, [<item:minecraft:dirt>]);
JEI.hideRecipe("minecraft:crafting", "crafttweaker:recipe_with_nbt");
```
that will add the recipe, but hide it from JEI and it works just fine.

So assuming you are talking about cc: tweaked, I looked into their code, and they way that they are adding recipes is what is causing the issue, I'm not too sure why they are adding recipes like they are, but I don't believe there is anything we can do about this, we (successfully) pass the `hideRecipe` call to JEI, from there it is up to JEI on how to handle it.

Once again, I'm sorry you waited 5 months for a reply.
