### ISSUE TITLE
[1.20.1] Hiding items by Regex breaks script if backslash is used

### ISSUE THREAD

**Issue by 630R63** [CraftTweaker/JEITweaker#38]
### Issue description

I was trying to hide the nukes that you can craft from Industrial Foregoing.
Disabling the recipe worked just fine, but when I wanted to also hide the items in JEI using Regex, the backslash escapes from the string and the script breaks

### Steps to reproduce

1. Get Industrial Foregoing, JEI, JeiTweaker and CraftTweaker going on Forge 47.3.12 (MC 1.20.1)
2. Use the script mentioned below and watch it fail because ";" was expected

### Script used

https://gist.github.com/630R63/c5aa11b204641a62047bb76703286d54

### The crafttweaker.log file

https://gist.github.com/630R63/0e80bd999b7d16e1c5e6d2aa8051a765

### Minecraft version

Other

### Forge version

47.3.12

### CraftTweaker version

14.0.44

### JEITweaker version

8.0.6

### JEI version

15.20.0.105

### Other relevant information

Don't mind the first errors from the log, that was just me trying things. Last error is all that matters

### The latest.log file

https://gist.github.com/630R63/b5722ec4fc9be73e1fc196360804d390

**Comment by jaredlll08** [comment]
The regex is passed in as a string, so you need to escape the backslash, the line should read like:
```
Jei.hideIngredientsByRegex("w*nuke\\w*");
```

**Comment by 630R63** [comment]
Thank you so much! That worked!
