### ISSUE TITLE
1.16.2 Missing license. 

### ISSUE THREAD

**Issue by Leomist** [CraftTweaker/JEITweaker#4]
In your META-INF folder file: mods.toml add 
license="Mojang Studios, All Rights Reserved"
before [[mods]

hope this helps.

**Comment by jaredlll08** [comment]
Look at previous issues.
https://github.com/CraftTweaker/JEITweaker/issues/3 

JEITweaker isn't on 1.16.2, so stop trying to use the 1.16.1 file on 1.16.2.

Even if it was, the mod is MIT, not all rights reserved.
Even if the mod was all rights reserved, I would *not* be licensing it to Mojang studios.

**Comment by Leomist** [comment]
apologies,  With The twitch app when you download "CraftTweaker-1.16.2-7.0.0.27.jar"
This mod is auto downloaded as a dependency. it cant be disabled without disabling the other.

**Comment by jaredlll08** [comment]
I ported it yesterday, it should be on curse for 1.16.2
