### ISSUE TITLE
[Suggestion] Allow hiding specific catalysts for a category of recipes

### ISSUE THREAD

**Issue by vahanbgs** [CraftTweaker/JEITweaker#5]
I suggest you add a way to hide specific catalysts for a category of recipes. For example if I have tinker's construct installed, when I look up crafting recipes with JEI, I will see that I can make those recipes using either the vanilla crafting table or tinkers' construct's crafting station. I would like to be able to hide the vanilla crafting table from the list of catalysts that can make crafting recipes.

**Comment by jaredlll08** [comment]
Firstly I would like to apologise for the late reply, I don't think github sent me notifications for this repository.

As far as I understand, JEI doesn't expose a method to hide Catalysts.

Make an issue report to JEI requesting it and then I can.
