### ISSUE TITLE
Enhancement: Hide by ModID/hide by REGEX with ability to use lambda

### ISSUE THREAD

**Issue by corhean** [CraftTweaker/JEITweaker#7]
Not an issue, but would like to see something that can hide item by MODID just like the removebyModid with the ability to use lambda for exception lists as well as a hide item by Regex. 

Would make removing large sections of things (looking at you colored block variants) way easier.

example, half-baked from the wiki...
mods.jei.JEI.hideByModid("appliedenergistics2", (name) => {
    return name in ae2Exclusions;
});

mods.jei.JEI.hideByRegex("minecraft:.*facade*");

**Comment by jaredlll08** [comment]
Fixed in https://github.com/CraftTweaker/JEITweaker/commit/d1b5681706eeace4d5c194164fb49b89b03b7766
