### ISSUE TITLE
[Issue] Scripts doesn't work on the server.

### ISSUE THREAD

**Issue by Nemesisfromdiscord** [CraftTweaker/JEITweaker#8]
The script file running smoothly in Singleplayer does not work on the server.

(1.16.4) No Errors appear in /ct syntax. 
Mods, scripts, config files are exactly the same. (Client and server)
Recipe Changes works fine. But items that need to be hidden are not hidden in JEI.
(Again, although it works fine on singleplayer, it doesn't work on the server.)

All versions of the mod have the same problem.
CT Log (server): https://pastebin.com/rnCw5yww

**Comment by jaredlll08** [comment]
I can't reproduce, I used:
```
mods.jei.JEI.hideItem(<item:minecraft:diamond_sword>);

mods.jei.JEI.addInfo(<item:minecraft:diamond>, ["§fwhite text §cred text§rreset text", "This is the second!", "third"]);

mods.jei.JEI.addInfo(<fluid:minecraft:water> * 1000, ["This is the first line!", "This is the second!", "third"]);
```
Joining the world everything is fine (sword is hidden, info is added)
/reload everything is fine (sword is hidden, info is added).
